In [2]:
print("Hello")

Hello


In [3]:
pip show numpy

Name: numpy
Version: 2.3.5
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2025, NumPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:

     * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials provided
        with the distribution.

     * Neither the name of the NumPy Developers nor the names of any
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
(7,)


In [9]:
arr2 = np.arange(1,102,4)
print(f"\n{arr2}")


[  1   5   9  13  17  21  25  29  33  37  41  45  49  53  57  61  65  69
  73  77  81  85  89  93  97 101]


In [11]:
arr1.reshape(1,7)

array([[1, 2, 3, 4, 5, 6, 7]])

In [13]:
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [19]:
arr_2d = np.array([1, 2, 3], ndmin=2)
print(arr_2d.shape)
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.size)

(1, 3)
[[1 2 3]]
2
3


In [16]:
arr_2d = np.array([1, 2, 3])
print(arr_2d.shape)

(3,)


In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
# Numpy Vectorized Operation
print("Addition :",arr1+arr2)
print(f"Subtraction :",arr1-arr2)
print(f"Multiply: ",arr1*arr2)
print(f"Division :",arr1/arr2)

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiply:  [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [37]:
arr = np.arange(1,6,1)
print(arr)
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))
print(np.log(2.71828183))

[1 2 3 4 5]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
1.0000000005668856


In [39]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
arr[0]

array([1, 2, 3, 4])

In [43]:
print(arr[0][0])

1


In [44]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [45]:
print(arr[0:2,1:3])

[[2 3]
 [6 7]]


In [46]:
print(arr[:3,3:])

[[ 4]
 [ 8]
 [12]]


In [47]:
arr[1:] = 100

In [48]:
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
data = np.arange(1,6)
mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean)/std_dev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [54]:
data = np.arange(1,11)
print(data[data>5])
print(data[(data>=5) & (data<=8)])

[ 6  7  8  9 10]
[5 6 7 8]
